# Generated by Django 4.2 on 2023-07-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_product_product_file_alter_product_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_color',
            new_name='product_year',
        ),
    ]
