# Generated by Django 4.2 on 2023-07-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_rename_product_color_product_product_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_brand',
            new_name='book_author',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_decs',
            new_name='book_decs',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_file',
            new_name='book_file',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='book_img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_isExist',
            new_name='book_isExist',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='book_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_year',
            new_name='book_year',
        ),
    ]
